export const ROUTES = {
  BLOG: '/blogs/',
  ROOT: '/',
  PAGE: '/home-page/icon/',
  SERVICESPAGE: '/service-page/',
  SERVICES: '/services/',
  APPROACHES: '/approaches/',
  APPROACHESPAGE: '/approach-page/',
  APPROACHICON: '/approach-page/icons/',
  CONTACTUS: '/contact-us-page/',
  ICON: '/icons/',
  CUSTOMERLOGO: '/home-page/logo-companies/',
  HEROIMAGE: '/home-page/',
  HOMEPAGEICON: '/home-page/icon/',
  CASE: '/cases/',
  CASEPAGE: '/cases-page/',
  CAREERPAGE: '/careers-page/',
  COMINGSOON: '/comingsoon-page/',
};
